### PR TITLE
Feature/012example

### PR DESCRIPTION
**Pull request by martytheparty**
Hey guys this PR has example 12 (11 is in another PR) to demonstrate the way dependencies are coded with the injector.

### CODE REVIEW

**Comment by adslaton** [comment]
This example 11 not 12

**Comment by adslaton** [comment]
Everything works as expected.

**Review by adslaton — APPROVED** [review]
No need to refactor just yet. Leave it as is and lets get feedback as we go.

**Comment by martytheparty** [comment]
Hi AD,

This is confusing... I added an 11th example as part of the data-source branch that is now merged.  So this example now fits into the 12th spot.

See you tomorrow!

Marty

**Comment by adslaton** [comment]
That is odd @martytheparty

**Pull request merged**
