### PR TITLE
Feature/examples

### PR DESCRIPTION
**Pull request by martytheparty**
I added 4 examples.  Here are couple of things to note:
1. I left the bower stuff in the first two examples.  I think that will make the learning curve less steep.
2. I couldn't use the data tags because there is a small bug in the injector.  It requires our footer object.  I will put a pull request that fixes this problem soon.

### CODE REVIEW

**Comment by adslaton** [comment]
Version 0.1.1 of this module has been released. It includes that footer changes that you added. I will continue to review the examples.

**Comment by adslaton** [comment]
I get a 404 on /bundles/inject.js. Some action items:
- Merge in the latest changes for the footer event
- Move bowe_components to the root of /example
- Move bundles to the root of /example

**Comment by martytheparty** [comment]
Hi AD, so where are you starting the server from?  I start my local server in the example's specific directory.

**Comment by adslaton** [comment]
That was the problem. However, it should not matter the server root. I took a look and you should change the bundleHost reference from `/bunldes/` to `bundles/`. That will make the path relative to the file that is using it.

**Comment by martytheparty** [comment]
/bundles/ => bundles/ sounds good... will do :)

**Comment by martytheparty** [comment]
OK everything seems to be golden now... I pushed these examples to http://www.injector.peachyga.com/ and they are all working.  I think these are a good start. I added an extra example that bundles CSS/HTML/JS.

**Comment by adslaton** [comment]
Examples 1 and 2 work. Examples 3, 4, and 5 still have console errors.

**Comment by martytheparty** [comment]
Hi AD, I am not sure what the errors you are see are, but do you mind checking them at http://www.injector.peachyga.com/ ?

I didn't include the libraries (injector.js and jquery.js) in the bower folder.  I will add them now.

**Comment by martytheparty** [comment]
I add the libraries into bower components... Hopefully that fixes the console error issues you mentioned earlier.

**Comment by adslaton** [comment]
Everything works now. Instead of having bower_components and bundles in each example move them to example/bower_components and example/bundles. The bower package would be enormous if we left them in each example. See the changes that I made in https://github.com/cnnlabs/injectorjs/tree/feature/examples-common-files/example

**Comment by martytheparty** [comment]
I moved the bower files as requested.

**Comment by adslaton** [comment]
Almost... you added bower components to the root injectorjs/. It should live at injectorjs/example/bower_components. Please delete the folder located at injectorjs/bower_components. In each example you would need to reference it as `../bower_componenes/*`

**Comment by ghost** [comment]
The README references example/index.html, which isn't in project.

I ran into that because I was unclear on how to view the examples ... and I wonder if writing documentation on how to wouldn't be more difficult that throwing in a simple server for the examples in the project so it is `npm start -> visit http://localhost:3000/` or whatever.

Also, if there was any interest in this PR being squashed into a single commit, I'd be happy to help. :-)

**Comment by martytheparty** [comment]
Hi Sam, I updated the README.md files to be more accurate.  AD and I decided to move the bower components up a level.  Sorry about the confusion.

**Comment by martytheparty** [comment]
AD, let me know if you want me to squash these commits into a single commit.

**Review by adslaton — APPROVED** [review]
Looks good.

**Pull request merged**
